version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_VAR_PIHOLE_API_KEY=${PIHOLE_API_KEY}
      - HOMEPAGE_VAR_RADARR_API_KEY=${RADARR_API_KEY}
      - HOMEPAGE_VAR_SONARR_API_KEY=${SONARR_API_KEY}
      - HOMEPAGE_VAR_PROWLARR_API_KEY=${PROWLARR_API_KEY}
      - HOMEPAGE_VAR_PLEX_API_KEY=${PLEX_API_KEY}
      - HOMEPAGE_VAR_NGINX_PROXY_MAN_USERNAME=${NGINX_PROXY_MAN_USERNAME}
      - HOMEPAGE_VAR_NGINX_PROXY_MAN_PASSWORD=${NGINX_PROXY_MAN_PASSWORD}
    ports:
      - 3000:3000
    volumes:
      - ./homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
