services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /data/jenkins:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent

