---
version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncting-chambinux
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ntokozo/Development/data/syncthing:/var/syncthing
    network_mode: host
    restart: unless-stopped

