---
version: "3"
x-podman:
  in_pod: false   
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncting-chambinux
    userns_mode: keep-id
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/Development/data/syncthing:/var/syncthing
    network_mode: host
    restart: unless-stopped


