---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets
- resources:
    cpu: true
    memory: true
    cputemp: true
    expanded: true
    disk:
        - /

- search:
    provider: brave
    target: _blank
